version: '3'
services:
  frontend:
    image: mateusreinert/frontend-kafka:1.0
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - kafka-network
    environment:
      REACT_APP_REST_HOST: https://1055-177-51-86-72.ngrok-free.app 
      REACT_APP_WS_HOST: wss://1055-177-51-86-72.ngrok-free.app 

networks:
  kafka-network:
    driver: bridge
